server:
  port: 8080


spring:
  datasource:
    driver-class-name: ${DATABASE.DRIVER}
    url: ${DATABASE.URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}

mybatis:
  type-aliases-package: com.rina.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true